LSG/urls.py
from django.urls import path
from LSG.views import *
app_name='LSG'
urlpatterns = [
    path('raahul/',raahul,name='raahul'),
]

MI/urls.py
from django.urls import path
from MI.views import *
app_name='MI'
urlpatterns = [
    path('rohit/',rohit,name='rohit'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import MI,LSG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('MI/',include('MI.urls')),
    path('LSG/',include('LSG.urls'))
]

LSG/models.py
from django.db import models

# Create your models here.

MI/models.py
from django.db import models

# Create your models here.

LSG/views.py
from django.shortcuts import render

# Create your views here.
def raahul(request):
    return render(request,'raahul.html')

MI/views.py
from django.shortcuts import render

# Create your views here.
def rohit(request):
    return render(request,'rohit.html')

templates/raahul.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is Classy KL Raahul's page</h1>
        <a href="{% url 'MI:rohit' %}">navigating to Rohit Page of MI App</a>
    </center>
</body>
</html>

templates/rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This is hitman's page</h1>
        <a href="{% url 'LSG:raahul' %}">navigating to KL Raahul Page of LSG App</a>
    </center>
</body>
</html>